apiVersion: v1
kind: Service
metadata:
  labels:
    name: payara-micro
  name: payara-micro
spec:
  type: LoadBalancer
  ports:
  - name: hazelcast
    port: 6900
  - name: micro
    port: 8080
  - name: debug
    port: 9009
  selector: 
    name: payara-micro
