apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    name: server
spec:
  selector:
    matchLabels:
      name: server
  replicas: 2
  template:
    metadata:
      labels:
        name: server
    spec:
      containers:
      - name: server
        image: pandrex247/payara-kubernetes-testing:server
        imagePullPolicy: Always
        ports:
        - name: server
          containerPort: 8080
