apiVersion: v1
kind: Service
metadata:
  labels:
    name: payara-micro
  name: payara-micro
spec:
  type: NodePort
  ports:
  - name: hazelcast
    port: 6900
  - name: micro
    port: 8080
    nodePort: 30001
  selector: 
    name: payara-micro
